import './globals.css'
import {Inter, Roboto} from 'next/font/google'
import NavBarMobile from "@/app/components/navBarMobile";
import NavBar from "@/app/components/navBar";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Aqua Flow',
  description: 'Generated by create next app',
}
const roboto = Roboto({
    weight: '400',
    subsets: ['latin'],
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} ${inter.className} `} style={{backgroundColor: "#F3F5F6"}}>
      <div className ="Mobile">
        <NavBarMobile/>
      </div>
      <div class= "Desktop">
        <NavBar/>
      </div>
          {children}
      </body>
    </html>
  )
}
