import { ReactNode } from 'react';
import NavBar from './components/NavBar';
import '../public/static/css/global.css';
import { Roboto } from 'next/font/google';
import Footer from './components/Footer';

export const metadata = {
    title: 'Aqua Flow',
    description: 'Generated by create next app',
};
const roboto = Roboto({
    weight: '400',
    subsets: ['latin'],
});

export default function RootLayout({ children }: { children: ReactNode[] }) {
    return (
        <html lang='en'>
            <body className={`${roboto.className} mx-auto h-screen min-h-screen w-full md:w-3/4`}>
                <NavBar />
                {children}
            </body>
            <footer className={`${roboto.className}  mx-auto w-full md:w-3/4`}>
                <Footer />
            </footer>
        </html>
    );
}
